# Instructions to set up your bot can be found here:
# https://docs.google.com/document/d/1BxjYt-RaZjAW8NIX0LDIUi8m6ngGAxeBFPKJEx90mjg
token: "OTcyNTQ4NTA0OTE4NTgxMzE4.YnaqYA.PqubtPGtjV3DACU1GZ1e2umF8Zs"
roles:
  - "ROLE ID" #1
  - "ROLE ID" #2
  - "ROLE ID" #3